import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{height: '40px', display: 'flex', justifyContent: 'flex-end', alignItems: 'center', columnGap: '12px'}}>
          <a href="/">首页</a>
          <a href="/sells">出售资产</a>
          <a href="/orders-update">测试更新订单状态</a>
        </header>
        {children}
      </body>
    </html>
  );
}
